spring:
  application:
    name: crawl-chung-khoan

  datasource:
    url: jdbc:postgresql://localhost:5432/crawl_chungkhoan
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24 hours

crawler:
  enabled: true
  default-interval: 5 # minutes
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_your_key}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_secret}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:your_bot_token}
  bot-username: ${TELEGRAM_BOT_USERNAME:your_bot_username}

logging:
  level:
    com.crawl.chungkhoan: DEBUG
    org.springframework.security: DEBUG

